### ISSUE TITLE
cinfo.c:47:invalidScanfFormatWidth

### ISSUE THREAD

**Issue by dcb314** [mrdotx/cinfo#5]
cinfo.c:47:13: error: Width 64 given in format string (no. 1) is larger than destination buffer 'g_host[50]', use %49s to prevent overflowing it. [invalidScanfFormatWidth]

Source code is

       if (fscanf(file, "%64s", g_host)) {

but

     g_host[50],

**Comment by mrdotx** [comment]
I have changed the format string. Thank you for your contribution.
